openai:
  api_key:
  base_url:
  temperature: 0.2  
  max_tokens: 2048
tool: 
  detect:
    groundingdino_config: pipeline/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
    model_path: weights/groundingdino_swint_ogc.pth
    device: cuda:0
    BOX_TRESHOLD: 0.35
    TEXT_TRESHOLD: 0.25
    AREA_THRESHOLD: 0.001
  ocr:
    dbnetpp_config: pipeline/mmocr/configs/textdet/dbnetpp/dbnetpp_resnet50-oclip_fpnc_1200e_icdar2015.py
    dbnetpp_path: weights/dbnetpp.pth
    maerec_config: pipeline/mmocr/configs/textrecog/maerec/maerec_b_union14m.py
    maerec_path: weights/maerec_b.pth
    device: cuda:0
    content: word.number
    cachefiles_path: cache_files
    BOX_TRESHOLD: 0.2
    TEXT_TRESHOLD: 0.25
  google_serper:
    serper_api_key: 
    snippet_cnt: 10
prompts:
  claim_generate: pipeline/prompts/claim_generate.yaml
  query_generate: pipeline/prompts/query_generate.yaml
  verify: pipeline/prompts/verify.yaml